language: elixir
otp_release: 19.0
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
before_script:
  - mix local.hex --force
  - mix do deps.get, deps.compile, compile --warnings-as-errors
script: "mix test --cover --trace --exclude will_fail:true"
