language: elixir
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
before_script:
  - mix local.hex --force
  - mix do deps.get, deps.compile, compile --warnings-as-errors
script: "mix test --cover --trace --exclude will_fail:true --exclude unstable_test:true"
