---
version: 2.1

jobs:
  build:
    parameters:
      version:
        description: Elixir version
        type: string
    docker:
      - image: elixir:<< parameters.version >>
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - testing-elixir-v<< parameters.version >>
      - run: MIX_ENV=test mix do deps.get, compile
      - run: mix test --cover --trace --exclude will_fail:true --exclude unstable_test:true
      - store_test_results:
          path: _build/test/lib/propcheck
      - save_cache:
          key: testing-elixir-v<< parameters.version >>
          paths:
            - _build
            - deps
            - ~/.mix
  lint:
    parameters:
      version:
        description: Elixir version
        type: string
    docker:
      - image: elixir:<< parameters.version >>
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: MIX_ENV=test mix do deps.get, compile
      - run: mix credo --strict

workflows:
  build:
    jobs:
      - build:
          name: "Elixir v1.5"
          version: "1.5"
      - build:
          name: "Elixir v1.6"
          version: "1.6"
      - build:
          name: "Elixir v1.7"
          version: "1.7"
      - build:
          name: "Elixir v1.8"
          version: "1.8"
      - lint:
          version: "1.8"
